services:
  - type: cron
    name: new_naukri
    env: python
    schedule: "0 3 * * *"  # every day at 8:30 AM IST
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
